### ISSUE TITLE
Does ESMpy support regridding using weights?

### ISSUE THREAD

**Issue by Yefee** [nawendt/esmpy-tutorial#1]
Hi, 

Does ESMpy support regridding using weights? ESMF does has, but I didnot find any information in ESMpy.

Thanks!

**Comment by nawendt** [comment]
I am not exactly sure, but I think you are asking about the weight files that are generated by ESMF. If that is your question, then I can say that ESMPy does not have the ability to generate weight files for reuse. However, the ESMPy developers have said that is something they want to do in the future.

If that does not answer your question, I would recommend getting into contact with the actual ESMPy developers (I am _not_ one) at [esmf_support@list.woc.noaa.gov](mailto:esmf_support@list.woc.noaa.gov). They have been very helpful to me thus far.
